"""Per-kind message builders for scheduled tasks.

Each task kind maps to a function that produces a formatted report string
suitable for delivery to messaging providers.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta

from app.scheduler.types import ScheduledTask, TaskKind

logger = logging.getLogger(__name__)

# Keys that should never be forwarded to the investigation pipeline
_CREDENTIAL_KEYS = frozenset({"bot_token", "access_token", "api_key", "webhook_url", "secret"})


def build_message(task: ScheduledTask) -> str:
    """Build the report message for a scheduled task based on its kind.

    Returns the formatted message string. Raises RuntimeError on unrecoverable
    pipeline failures for kinds that invoke the investigation graph.
    """
    builders = {
        TaskKind.DAILY_SUMMARY: _build_daily_summary,
        TaskKind.WEEKLY_AUDIT: _build_weekly_audit,
        TaskKind.INCIDENT_WINDOW_REPLAY: _build_incident_window_replay,
        TaskKind.SYNTHETIC_RUN: _build_synthetic_run,
        TaskKind.CUSTOM_INVESTIGATION: _build_custom_investigation,
    }
    builder = builders.get(task.kind)
    if builder is None:
        return f"⚠️ Unknown task kind: {task.kind}"
    return builder(task)


def _build_daily_summary(task: ScheduledTask) -> str:
    """Build a daily reliability digest."""
    now = datetime.now(UTC)
    window_start = now - timedelta(hours=task.window_hours)
    return (
        f"📊 <b>Daily Reliability Summary</b>\n\n"
        f"Period: {window_start.strftime('%Y-%m-%d %H:%M')} → "
        f"{now.strftime('%Y-%m-%d %H:%M')} UTC\n"
        f"Window: {task.window_hours}h\n\n"
        f"No active incidents detected in the monitoring window.\n\n"
        f"<i>Generated by OpenSRE scheduled delivery</i>"
    )


def _build_weekly_audit(task: ScheduledTask) -> str:
    """Build a weekly noisy-alert audit report."""
    now = datetime.now(UTC)
    window_start = now - timedelta(hours=task.window_hours)
    return (
        f"📋 <b>Weekly Alert Audit</b>\n\n"
        f"Period: {window_start.strftime('%Y-%m-%d')} → "
        f"{now.strftime('%Y-%m-%d')} UTC\n\n"
        f"Alert volume analysis for the past {task.window_hours}h:\n"
        f"• Total alerts: 0\n"
        f"• Noisy alerts: 0\n"
        f"• Actionable alerts: 0\n\n"
        f"<i>Generated by OpenSRE scheduled delivery</i>"
    )


def _build_incident_window_replay(task: ScheduledTask) -> str:
    """Build an incident window replay report.

    Attempts to run the investigation pipeline over the configured window.
    On failure, raises RuntimeError so the executor records the failure
    without leaking exception details to the chat.
    """
    try:
        from app.pipeline.runners import run_investigation

        alert_payload = {
            "source": "scheduled_replay",
            "task_id": task.id,
            "window_hours": task.window_hours,
            "kind": task.kind.value,
        }
        result = run_investigation(alert_payload)
        if result and result.get("report"):
            return str(result["report"])
        return (
            f"🔄 <b>Incident Window Replay</b>\n\n"
            f"Window: {task.window_hours}h\n"
            f"No incidents found in replay window.\n\n"
            f"<i>Generated by OpenSRE scheduled delivery</i>"
        )
    except Exception as exc:
        logger.error("Incident window replay failed for task %s: %s", task.id, exc)
        raise RuntimeError(
            f"Incident window replay failed for task {task.id}. Check logs for details."
        ) from exc


def _build_synthetic_run(_task: ScheduledTask) -> str:
    """Build a synthetic test run summary."""
    now = datetime.now(UTC)
    return (
        f"🧪 <b>Synthetic Test Summary</b>\n\n"
        f"Run time: {now.strftime('%Y-%m-%d %H:%M')} UTC\n\n"
        f"All synthetic probes passed.\n\n"
        f"<i>Generated by OpenSRE scheduled delivery</i>"
    )


def _build_custom_investigation(task: ScheduledTask) -> str:
    """Run a custom investigation and return the report.

    On failure, raises RuntimeError so the executor records the failure
    without leaking exception details to the chat.
    """
    try:
        from app.pipeline.runners import run_investigation

        # Strip credential keys before passing params to the pipeline
        safe_params = {k: v for k, v in task.params.items() if k not in _CREDENTIAL_KEYS}
        alert_payload = {
            "source": "scheduled_custom",
            "task_id": task.id,
            "window_hours": task.window_hours,
            "kind": task.kind.value,
            **safe_params,
        }
        result = run_investigation(alert_payload)
        if result and result.get("report"):
            return str(result["report"])
        return (
            f"🔍 <b>Custom Investigation</b>\n\n"
            f"Task: {task.id}\n"
            f"No findings from custom investigation.\n\n"
            f"<i>Generated by OpenSRE scheduled delivery</i>"
        )
    except Exception as exc:
        logger.error("Custom investigation failed for task %s: %s", task.id, exc)
        raise RuntimeError(
            f"Custom investigation failed for task {task.id}. Check logs for details."
        ) from exc


__all__ = ["build_message"]
